### ISSUE TITLE
Exchange: FTX

### ISSUE THREAD

**Issue by just-nilux** [TheFourGreatErrors/alpha-rptr#1]
Hey buddy, this is an awesome project! Great stuff and thanks for sharing this open-source.
Are you considering adding FTX? In terms of liquidity, innovations, plenty of a pairs to trade and the community FTX is really overtaking Bitmex...

I would buy you a beer :)

**Comment by TheFourGreatErrors** [comment]
Hello and thank you, I will most likely add FTX, not sure about ETA for the implementation though. I will probably give FTX implementation more priority, since many people have started using this exchange recently. I am also planning to add Bybit and Phemex(a new exchange with rebate similar to BitMEX - looks decent from what I saw, also they offer FIX api for market makers, so they are probably legit and serious about what they are doing) as well. BTW take a look at Binance futures its really good when it comes to fees and liquidity and they have low min tick, so your limit orders have higher chance of getting filled even when the market is moving away from your order.

**Comment by nomad5am** [comment]
yep! the team behind ftx is well-known and absolutely solid and I guess if you support bitmex, binance-futures and ftx you will have the most future-proof exchanges supported and you can wrap that part of your project up; focus then more on the core features. I see many projects here wanting to support every possible exchange (look at what happened to ccxt, what a mess) and it will be impossible to maintain and update all of those. I like your approach. Have a look at the ftx wrapper of askmike, very solid: 

https://github.com/askmike/ftx-api-ws
https://github.com/askmike/ftx-api-rest

I'll quite busy these days but will try to contribute a little bit to your project soon. Got some ideas you might like ;)
Keep it on!
